modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "theatrical"
version = "${version}"
displayName = "Theatrical"
authors = "Rushmead,bright_spark"
description = '''
Theatrical, bringing the theatre to Minecraft.
'''
#logoFile = ""

[[dependencies.theatrical]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
