modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "theatrical"
version = "${version}"
displayName = "Theatrical"
authors = "Rushmead,bright_spark"
description = '''
Theatrical, bringing the theatre to Minecraft.
'''
#logoFile = ""


[[mixins]]
config = "theatrical-common.mixins.json"

[[dependencies.theatrical]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2.75-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.15,)"
ordering = "AFTER"
side = "BOTH"
