modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "theatrical"
version = "${version}"
displayName = "Theatrical"
authors = "Rushmead,bright_spark"
description = '''
Theatrical, bringing the theatre to Minecraft.
'''
#logoFile = ""


[[mixins]]
config = "theatrical-common.mixins.json"

[[mixins]]
config = "theatrical-forge.mixins.json"

[[dependencies.theatrical]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatrical]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
