name: Standard Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Run gradle tasks [build publish]
        uses: gradle/gradle-build-action@v2
        env:
          SNAPSHOT: false
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          arguments: "build publish curseforgePublish modrinth"
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build-output
          path: ./**/libs/*.jar
  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: gradle-build-output
      - name: Release to Github
        if: startsWith(github.ref, 'refs/tags/')
        uses: "softprops/action-gh-release@v1"
        with:
          body_path: "./CHANGELOG.md"
          prerelease: false
          files: "./+(forge|fabric)/build/libs/*+@(mc+([0-9]).+([0-9]).+([0-9])).jar"
