name: Standard Release

on:
  push:
    branches:
      - "**"

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, '[publish]')
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Run gradle tasks [build publish]
        uses: gradle/gradle-build-action@v2
        env:
          SNAPSHOT: false
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          arguments: "build publishMods"
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build-output
          path: ./**/libs/*.jar